module.exports = function (grunt) {

  require('jit-grunt')(grunt, {
    sprite: 'grunt-spritesmith'
  });

  // Define the configuration for all the tasks
  grunt.initConfig({

    modernizr: {
      dev: {
        'crawl': false,
        'parseFiles': false,
        'customTests': [],
        'dest': "./src/assets/scripts/modernizr.js",
        'tests': [
          "touchevents"
        ],
        'options': [
          'domPrefixes',
          'prefixes',
          'addTest',
          'atRule',
          'hasEvent',
          'mq',
          'prefixed',
          'prefixedCSS',
          'prefixedCSSValue',
          'testAllProps',
          'testProp',
          'testStyles',
          'setClasses'
        ],
        'uglify': false
      }
    },

    sass_globbing: {
      main: {
        files: {
          './src/styles/_main.scss': './src/styles/main/**/*.scss'
        },
        options: {
          useSingleQuotes: false,
          signature: '// This file is generated by a \'grunt-sass-globbing\' plugin. Please, do NOT edit it!'
        }
      }
    },

    sprite: {
      dev: {
        src: './src/sprite-png-src/**/*.png',
        dest: './src/assets/sprite.png',
        destCss: './src/styles/_sprites.scss',
        imgPath: '~/assets/sprite.png?' + (new Date().getTime()),
        padding: 2,
        retinaSrcFilter: './src/sprite-png-src/**/*@2x.png',
        retinaDest: './src/assets/sprite@2x.png',
        retinaImgPath: '~/assets/sprite@2x.png?' + (new Date().getTime())
      }
    },

    svgstore: {
      options: {
        svg: {
          // will add and overide the the default xmlns="http://www.w3.org/2000/svg" attribute to the resulting SVG.
          xmlns: 'http://www.w3.org/2000/svg',
          'xmlns:xlink': 'http://www.w3.org/1999/xlink',
          style: 'width:0;height:0;visibility:hidden;position:absolute;'
        }
      },
      sprite: {
        options: {
          includedemo: true
        },
        files: {
          './src/assets/sprite.svg': ['./src/sprite-svg-src/*.svg']
        }
      }
    },

    copy: {
      svgxuse: {
        files: [{
          expand: true,
          dest: './src/assets/scripts/',
          cwd: './node_modules/svgxuse/',
          src: 'svgxuse.min.js'
        }]
      }
    }


  });

  grunt.registerTask('build-modernizr', ['modernizr']);
  grunt.registerTask('build-sprite-png', ['sprite']);
  grunt.registerTask('build-sprite-svg', ['svgstore']);
  grunt.registerTask('copy-assets', ['copy']);

  grunt.registerTask('build', [
    'sass_globbing',
    'copy-assets',
    'build-modernizr',
    'build-sprite-png',
    'build-sprite-svg'
  ]);

  grunt.registerTask('default', ['build']);

};
